name: Wellnesse Flow
on:
 schedule:
  - cron: '45 13 * * *'
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
       node-version: '18.x'
    - name: Build
      run: |
        ./node_modules/.bin/cypress install
        npx run test
